### ISSUE TITLE
Help Center

### ISSUE THREAD

**Issue by bootleg224** [getopenwater/cmsresearch#2]
Read https://docs.raytha.com/articles/installation.html

Implement this theme: 
https://github.com/bootleg224/FrontTheme

Specifically implement 
- [ ] https://bootleg224.github.io/FrontTheme/demo-help-desk/index.html
- [ ] https://bootleg224.github.io/FrontTheme/demo-help-desk/listing.html
- [ ] https://bootleg224.github.io/FrontTheme/demo-help-desk/article-overview.html

Home page for search articles, that pull categories and descrptions
Listing page that shows all articles for a category
Single article pages

Try to implement as much as you can and ask questions where you are stuck like "how do i implement" a breadcrumb
![image](https://github.com/getopenwater/cmsresearch/assets/7950956/ad8a54bc-5716-4e2b-a661-7e1485d8a6ba)

The things that require postback, you can put in a CSS class not-implemented and use the color pink to signal that this doesn't work yet because it is beyond the scope of using raytha without further context
![image](https://github.com/getopenwater/cmsresearch/assets/7950956/46a93528-efc9-4aee-849b-da468afe8601)

For sample data you can use the categories and content from 10 or so articles from here: https://help.getopenwater.com/

Since this is mostly raytha out of the box just post a link to the azure website where it is hosted, and ensure the SQL is up to date

**Comment by apexdodge** [comment]
Helpful videos for this project:

https://www.youtube.com/watch?v=6iXkLkaWH6Q
https://www.youtube.com/watch?v=n80NjVA7uyM

**Comment by JaroslavENDER** [comment]
https://raytha.awards-dev-test-server.office.getfullstack.co:8006
jaroslav.end<span>er@</span>test.mail / 12345678
