### ISSUE TITLE
Job Board with Custom Code

### ISSUE THREAD

**Issue by bootleg224** [getopenwater/cmsresearch#3]
- [ ] https://github.com/getopenwater/cmsresearch/issues/2 implement there the "Was this article helpful" functionality.  This will require custom code.  @apexdodge to help explain the best way to do it

- [ ] Now let's move onto a new site for https://bootleg224.github.io/FrontTheme/demo-jobs/index.html

- [ ] implement job listing, job view page; no need yet for apply to job page
- [ ] Implement post job page https://bootleg224.github.io/FrontTheme/demo-jobs/post-job.html  this will require server side code, use the same pattern @apexdodge suggested

**Comment by apexdodge** [comment]
Helpful video for this project:

https://www.youtube.com/watch?v=RkgyK_wSPEE

**Comment by JaroslavENDER** [comment]
Added "Was this article helpful" counter
https://raytha.awards-dev-test-server.office.getfullstack.co:8006/articles/OpenWater-Video-Tutorial-Training

Implemented post job page
https://raytha-job.awards-dev-test-server.office.getfullstack.co:8006/post-job
jaroslav.ende<span>r@</span>test.mail / 12345678
