### ISSUE TITLE
Plan to Remove Custom Code and Still have Job Board Implemented

### ISSUE THREAD

**Issue by bootleg224** [getopenwater/cmsresearch#4]
From here we should have a discussion of ways to improve raytha core to make both the help center and job board easier and more intuitive to build.  Task to be specified

**Comment by bootleg224** [comment]
Implement top item from roadmap: https://github.com/RaythaHQ/raytha/discussions/172
https://github.com/RaythaHQ/raytha/issues/177

Then use this feature to replace custom code to still have job board implementation

**Comment by JaroslavENDER** [comment]
Added PR:
https://github.com/RaythaHQ/raytha/pull/183

Refactored with functions:
https://raytha.awards-dev-test-server.office.getfullstack.co:8006
https://raytha-job.awards-dev-test-server.office.getfullstack.co:8006
jaroslav.ender@test.mail / 12345678
