### ISSUE TITLE
Menus QA

### ISSUE THREAD

**Issue by apexdodge** [getopenwater/cmsresearch#6]
1) When reordering menu items, on success, show little pop up of success like we have when reordering fields in a Content Type like so:

![image](https://github.com/getopenwater/cmsresearch/assets/777005/54a988ca-b870-4693-b74f-207761bc0a6a)

2) Left side menu, "Menus" should be highlighted when selected, like it works with other nav items

![image](https://github.com/getopenwater/cmsresearch/assets/777005/52d188b0-03cf-4695-b66a-2654f95255d2)

vs 

![image](https://github.com/getopenwater/cmsresearch/assets/777005/83a28621-d876-4689-acb0-b213630e66a7)

3) Menu Items header seems to have rounded corners on each column:

![image](https://github.com/getopenwater/cmsresearch/assets/777005/e1e7361f-2a2f-4f33-95c3-973b8f9980fa)

Should be smooth like:

![image](https://github.com/getopenwater/cmsresearch/assets/777005/93e65524-3fa2-4124-bc0e-22b41b8754c2)

4) The menu commands should be a filterable category in Audit Logs

![image](https://github.com/getopenwater/cmsresearch/assets/777005/6c4b5e19-8c4c-4218-a449-98ead88116b9)

5) RaythaFunctions too for that matter

6) "Parent Menu Item" -- lets sentence case it to "Parent menu item"

![image](https://github.com/getopenwater/cmsresearch/assets/777005/cf7130df-e338-464d-b34a-dda2c7a38616)

7) For UI consistency, when are you in the context of a Menu Item, lets remove these other menu items and only show the `Delete menu item` menu item

![image](https://github.com/getopenwater/cmsresearch/assets/777005/4f7661f3-9144-4d5f-ba37-6cb5a74e6a3d)

The user can click <-- Back to get back to menu items

**Comment by JaroslavENDER** [comment]
Fixed https://raytha.awards-dev-test-server.office.getfullstack.co:8006/raytha/menus
